/* The wind Max actually sailed in — C1 + C2 of the chart catalogue.

   EVIDENCE MODULE: every value rides MAXDATA (modules/maxdata.js), generated by
   scripts/gen_max_constants.py from the committed, cleaned instrument file.
   Class: MEASURED at the boat — not a buoy 10-40 nm away and not a model. This
   is the layer the tracker never had (I18: the tracker carries no wind).

   FORM: direction is the story, strength is the magnitude, so TWD takes the one
   y-axis and TWS rides a sequential single-hue ramp (dataviz: sequential = one
   hue light->dark; never a rainbow). Deliberately NOT a dual-axis chart.

   THE TRAP, stated on the chart: cumulative rotation is sample-rate dependent —
   the same wind gives 5,119 deg at 1-min medians, 1,255 at 5-min, 697 at 15-min
   — and net rotation flips sign between timescales. So this leads with the
   RANGE, which is stable, and names its timescale. An earlier memo draft
   published "2,216 deg, net -561" and it was withdrawn. */
"use strict";

registerModule({
  id: 'maxwind',
  deps: [],
  section: {
    kind: 'plot',
    height: 'min(520px, 108vw)',
    title: 'The wind Max actually sailed in',
    note: '<b>Every wind number elsewhere on this page is a buoy 10–40 nm away or a model. ' +
      'This is the breeze at the boat — 46 hours of it, measured.</b> ' +
      'Each dot is a 5-minute median: wind <b>direction</b> up the y-axis, wind <b>strength</b> as ' +
      'the dot shade (pale = drifting, dark = pressure). ' +
      'The shaded band is <b>the dawn park</b>, the segment where the phase ledger books ' +
      '+273 min against Katara56 — the wind there covered a range of <b>348°</b>, essentially the ' +
      'whole compass, with the breeze under 3 kt for 38% of the window. It was not merely light; ' +
      'it was directionless. ' +
      '<i>Read the range, not a total: cumulative rotation depends entirely on how fast you sample ' +
      '(1,255° at this 5-minute timescale, 697° at 15-minute, 5,119° at 1-minute), so a “total ' +
      'rotation” figure without a stated timescale means nothing.</i> ' +
      '<i>The axis wraps at north:</i> a trace leaving the top reappears at the bottom — that is the ' +
      'same wind continuing to rotate, not a second breeze and not a gap in the data. ' +
      'Evidence class: <b>measured</b> — Max\'s own instruments, cleaned (a −26° heading flicker on ' +
      '7% of samples is repaired; see the data notes).',
  },
  build(ctx) {
    const { h, cfg } = ctx;
    const MONO = 'SF Mono, Menlo, monospace';
    const W = (typeof MAXDATA !== 'undefined' && MAXDATA.wind) || [];
    if (!W.length) return { traces: [], layout: h.BASE() };
    const P = MAXDATA.park;

    /* Sequential ramp: ONE hue, light -> dark (dataviz colour formula). Steps
       are the shell's blue family so the page reads as one system. */
    const RAMP = [[0, '#DCE9F5'], [0.25, '#A9C8E6'], [0.5, '#6E9FD0'],
                  [0.75, '#3D74B4'], [1, '#1B4A85']];

    const traces = [{
      type: 'scattergl', mode: 'markers',
      x: W.map(p => p.t), y: W.map(p => p.d),
      marker: {
        size: h.narrow() ? 4.5 : 5.5, color: W.map(p => p.s),
        colorscale: RAMP, cmin: 0, cmax: 14,
        colorbar: {
          title: { text: 'TWS (kt)', font: h.AXFONT }, thickness: 10,
          len: 0.55, y: 0.5, tickfont: { ...h.AXFONT, size: 9 }, outlinewidth: 0,
        },
        line: { width: 0 },
      },
      customdata: W.map(p => p.s),
      hovertemplate: '%{x}<br>direction %{y:.0f}°<br>strength %{customdata:.1f} kt<extra></extra>',
      name: 'measured wind',
    }];

    /* The park band. Shaded region + a VERTICAL label inside its own band, so it
       never claims the y>1 paper row (phase labels) or the top in-plot row
       (event markers) — the label-lane rule. */
    const shapes = [{
      type: 'rect', xref: 'x', yref: 'paper', x0: P.from, x1: P.to, y0: 0, y1: 1,
      fillcolor: '#17293A', opacity: 0.055, line: { width: 0 }, layer: 'below',
    }];
    const annotations = [{
      xref: 'x', yref: 'paper', x: P.from, xanchor: 'left', y: 0.5, showarrow: false,
      textangle: -90, text: `THE DAWN PARK · ${P.rangeDeg}° of direction`,
      font: { size: h.narrow() ? 8.5 : 9.5, color: '#41505E', family: MONO },
    }];

    const layout = {
      ...h.BASE(),
      margin: { ...h.BASE().margin, t: 18, r: h.narrow() ? 54 : 74 },
      shapes, annotations,
      xaxis: { ...h.GAX, type: 'date',
        title: { text: `Time (${cfg.time.tzLabel})`, font: h.AXFONT } },
      yaxis: { ...h.GAX, range: [0, 360], dtick: 90,
        tickvals: [0, 90, 180, 270, 360],
        ticktext: ['N', 'E', 'S', 'W', 'N'],
        title: { text: 'Wind direction (from)', font: h.AXFONT } },
      showlegend: false,
    };
    return { traces, layout };
  },
});
